include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_put_required_named_parameters_first: true
    always_use_package_imports: true
    avoid_double_and_int_checks: true
    avoid_init_to_null: true
    avoid_js_rounded_ints: true
    avoid_multiple_declarations_per_line: true
    avoid_renaming_method_parameters: true
    avoid_returning_this: true
    avoid_unused_constructor_parameters: true
    avoid_positional_boolean_parameters: true
    await_only_futures: true
    cascade_invocations: true
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: true
    file_names: true
    no_leading_underscores_for_local_identifiers: true
    prefer_foreach: true
    prefer_single_quotes: true
    require_trailing_commas: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true
    unnecessary_getters_setters: true